### ISSUE TITLE
R help problem

### ISSUE THREAD

**Issue by rmendels** [ptaconet/modisfast#12]
Please refer to this https://github.com/openjournals/joss-reviews/issues/7343.

I have updated to your latest on github just a few minutes ago, so that you know what version I am referring to.  I am running the latest R and RStudio.  When I go "?modisfast"  a proper page comes up,  but if I then click on "[Package modisfast version 0.9.1 [Index](http://127.0.0.1:18327/help/00Index.html)]"    I get "URL '/help/00Index.html' not found" .  The appropriate function help do work,  ie "?mf_download_data"

**Comment by ptaconet** [comment]
you mean, when you click in what I point out with the red arrow in the attached image ?
![Capture d’écran du 2024-10-30 18-57-45](https://github.com/user-attachments/assets/25ba59e9-19a3-476b-b42b-f7bd7e6685e5)

**Comment by ptaconet** [comment]
I am not getting this problem, even when trying to install the development version of the package on another machine.. 
Maybe restarting your R session may solve the problem ? see https://stackoverflow.com/questions/67247051/url-help-library-package-r-html-00index-html-not-found-when-using-devtools

**Comment by rmendels** [comment]
@ptaconet   Yes that is what I mean.  I will try on another computer in a bit,  and will let you know.

**Comment by rmendels** [comment]
@ptaconet tried on a new computer, it worked.  I am closing this
