### ISSUE TITLE
Bug in function .testLogin(): unused argument when calling mf_login()

### ISSUE THREAD

**Issue by V-Agudetse** [ptaconet/modisfast#14]
Hi @ptaconet,

I found this bug in https://github.com/ptaconet/modisfast/blob/110ae2a04c599baeba6bfd33cb0e5636165c41d7/R/internal_tests.R#L48

Raises the following error:

```
Error in mf_login(credentials, source = "earthdata") : 
  unused argument (source = "earthdata")
```

as source is not an argument in mf_login() (anymore?).

**Comment by ptaconet** [comment]
Thanks for raising this bug @V-Agudetse , solved with commit https://github.com/ptaconet/modisfast/commit/0ff75105d6d40bae98b4bc641d4e76dd8e7cf848
