### ISSUE TITLE
[JOSS Review] Citation formatting

### ISSUE THREAD

**Issue by V-Agudetse** [ptaconet/modisfast#16]
Hi @ptaconet, this is my only remaining comment related to https://github.com/openjournals/joss-reviews/issues/7343; it's a very minor issue.

According to the style guide (https://pandoc.org/MANUAL.html) the titles of the .bib citation file should be in sentence case. See this section specifically: : https://pandoc.org/MANUAL.html#capitalization-in-titles

Cheers,

Victòria

**Comment by ptaconet** [comment]
Hi @V-Agudetse , 

Thanks for this detail. 
In the document https://pandoc.org/MANUAL.html#capitalization-in-titles , it is written : 

> If you are using a bibtex or biblatex bibliography, then observe the following rules:
> 
>   -  English titles should be in title case. 

I am actually using a bibtex bibliography, so I guess the titles should be in title case rather than in lower case ? Or am I loosing some detail here ?

**Comment by V-Agudetse** [comment]
Yes, forgive me! I meant title case. Examples here: https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case

**Comment by ptaconet** [comment]
Ok, fixed in commit https://github.com/ptaconet/modisfast/issues/16 !
