### ISSUE TITLE
MOD14 and MYD04_L2 are missing (not supported)

### ISSUE THREAD

**Issue by LuoXu-THU** [ptaconet/modisfast#7]
It is a very nice and fast tool! Love it!!
But it mentioned: 
Currently modisfast supports download of 77 data collections, extracted from the following meta-collections :

MOD14.061 and MYD04_L2.061 are very useful datasets and seem not to be able to use this tool to download.

Also, what if I want to make the Polygen in your example as a box [-180,83,-50,14], could you please tell me how to change it?

Thanks!

**Comment by ptaconet** [comment]
Hi @LuoXu-THU , thanks for you message ! 
Unfortunately, access to MOD14.061 and MYD04_L2.061 are not supported at this time. I might provide access when I have time (not before next year...). The catalog of supported collection can be viewed with the function  mf_list_collections().

Regarding your 2nd question, maybe the easiest is to use a tool such as  https://wktmap.com/  to draw a WKT polygon on an interactive map. You may then just copy and paste the WKT string in your R script.

**Comment by LuoXu-THU** [comment]
Thanks! Do you know is there any tool I can use to download  MOD14.061 and MYD04_L2.061 fast?

**Comment by ptaconet** [comment]
no I don't know :(
