### ISSUE TITLE
Citations in Paper

### ISSUE THREAD

**Issue by rmendels** [ptaconet/modisfast#9]
Please refer to this [JOSS review issue](https://github.com/openjournals/joss-reviews/issues/7343)

R packages on CRAN have a formal citation even if there isn't a paper,  as does the OPeNDAP protocol.  It is good that you link to these,  but the formal citations should also be in the references.  This does not count in the paper word count limit.

**Comment by ptaconet** [comment]
@rmendels please indicate if everything is good for you (or if you have a suggestion for a better citation of OPeNDAP) so that I can close the issue :)

**Comment by rmendels** [comment]
@ptaconet -  I actually emailed OPenDAP support the other day about their preferred citation and have not received a reply which has happened a number of times recently.  I am good with what you have.  Thanks.
